apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-worker-config
  namespace: fiapgames
  labels:
    app: payments-worker
data:
  RabbitMq__HostName: "rabbitmq.fiapgames.svc.cluster.local"
  RabbitMq__Port: "5672"
  RabbitMq__VirtualHost: "/"
  RabbitMq__OrderPlacedQueue: "order-placed-queue"
  RabbitMq__PaymentProcessedCatalogQueue: "payment-processed-catalog-queue"
  RabbitMq__PaymentProcessedNotificationsQueue: "payment-processed-notifications-queue"
