apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
  namespace: fiapgames
  labels:
    app: payments-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z -w 2 postgres.fiapgames.svc.cluster.local 5432; do
                echo "waiting for postgres..."
                sleep 2
              done
      containers:
        - name: payments-api
          image: lucasceifador/fiapgames-payments-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: payments-api-config
            - secretRef:
                name: payments-api-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
