apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
  namespace: fiapgames
  labels:
    app: payments-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      containers:
        - name: payments-api
          image: lucasceifador/fiapgames-payments-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: payments-api-config
            - secretRef:
                name: payments-api-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
